Cards_values={"Ace":11,"Two":2,"Three":3,"Four":4,"Five":5,"Six":6,"Seven":7,"Eight":8,"Nine":9,"Ten":10,"Jack":10,"Queen":10,"King":10}

Suits={"Spades":Cards_values,"Hearts":Cards_values,"Clubs":Cards_values,"Diamonds":Cards_values}

Ace_Cards=["Ace of Spades","Ace of Hearts","Ace of Clubs","Ace of Diamonds"]

Single_Deck={"Ace of Spades":Suits["Spades"]["Ace"],
             "Ace of Hearts":Suits["Hearts"]["Ace"],
             "Ace of Clubs":Suits["Clubs"]["Ace"],
             "Ace of Diamonds":Suits["Diamonds"]["Ace"],
             "Two of Spades":Suits["Spades"]["Two"],
             "Two of Hearts":Suits["Hearts"]["Two"],
             "Two of Clubs":Suits["Clubs"]["Two"],
             "Two of Diamonds":Suits["Diamonds"]["Two"],
             "Three of Spades":Suits["Spades"]["Three"],
             "Three of Hearts":Suits["Hearts"]["Three"],
             "Three of Clubs":Suits["Clubs"]["Three"],
             "Three of Diamonds":Suits["Diamonds"]["Three"],
             "Four of Spades":Suits["Spades"]["Four"],
             "Four of Hearts":Suits["Hearts"]["Four"],
             "Four of Clubs":Suits["Clubs"]["Four"],
             "Four of Diamonds":Suits["Diamonds"]["Four"],
             "Five of Spades":Suits["Spades"]["Five"],
             "Five of Hearts":Suits["Hearts"]["Five"],
             "Five of Clubs":Suits["Clubs"]["Five"],
             "Five of Diamonds":Suits["Diamonds"]["Five"],
             "Six of Spades":Suits["Spades"]["Six"],
             "Six of Hearts":Suits["Hearts"]["Six"],
             "Six of Clubs":Suits["Clubs"]["Six"],
             "Six of Diamonds":Suits["Diamonds"]["Six"],
             "Seven of Spades":Suits["Spades"]["Seven"],
             "Seven of Hearts":Suits["Hearts"]["Seven"],
             "Seven of Clubs":Suits["Clubs"]["Seven"],
             "Seven of Diamonds":Suits["Diamonds"]["Seven"],
             "Eight of Spades":Suits["Spades"]["Eight"],
             "Eight of Hearts":Suits["Hearts"]["Eight"],
             "Eight of Clubs":Suits["Clubs"]["Eight"],
             "Eight of Diamonds":Suits["Diamonds"]["Eight"],
             "Nine of Spades":Suits["Spades"]["Nine"],
             "Nine of Hearts":Suits["Hearts"]["Nine"],
             "Nine of Clubs":Suits["Clubs"]["Nine"],
             "Nine of Diamonds":Suits["Diamonds"]["Nine"],
             "Ten of Spades":Suits["Spades"]["Ten"],
             "Ten of Hearts":Suits["Hearts"]["Ten"],
             "Ten of Clubs":Suits["Clubs"]["Ten"],
             "Ten of Diamonds":Suits["Diamonds"]["Ten"],
             "Jack of Spades":Suits["Spades"]["Jack"],
             "Jack of Hearts":Suits["Hearts"]["Jack"],
             "Jack of Clubs":Suits["Clubs"]["Jack"],
             "Jack of Diamonds":Suits["Diamonds"]["Jack"],
             "Queen of Spades":Suits["Spades"]["Queen"],
             "Queen of Hearts":Suits["Hearts"]["Queen"],
             "Queen of Clubs":Suits["Clubs"]["Queen"],
             "Queen of Diamonds":Suits["Diamonds"]["Queen"],
             "King of Spades":Suits["Spades"]["King"],
             "King of Hearts":Suits["Hearts"]["King"],
             "King of Clubs":Suits["Clubs"]["King"],
             "King of Diamonds":Suits["Diamonds"]["King"]
}
